### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by MDaniel592** [TheRootED24/GL.iNET-B3000-MARBLE-fit-images#1]
Hello, could you please update the readme and clarify the installation process?

I checked the latest commit and I am not sure if the GL-B3000 can be upgrade via luci from the stock firmware.

Regards!

**Comment by TheRootED24** [comment]
To flash to openwrt, use the stock glinet webui --> upgrade firmware --> local upgrade
download and unzip the openwrt (.img) file.
select the above file or drag and drop into onto the glinet firmware upgrade screen
select upgrade.

To upgrade in openwrt (when needed) , use sysupgrade.tar from luci system-->Backup/Flash Firmware.

for more info, and development discussion, see here --> https://forum.openwrt.org/t/ipq5018-glinet-b3000-info/210771/216?u=hostle

I'll update the readme when i get a chance.
